spring:
  datasource:
    url: jdbc:h2:file:/Users/ivoloshanovskii/demopr
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true

#server:
#  error:
#    include-message: always
#    include-binding-errors: always
#    include-stacktrace: never
